### ISSUE TITLE
Can I migrate from old menubar repo?

### ISSUE THREAD

**Issue by yceballost** [amaurymartiny/menubar#12]
Hi @amaurymartiny!

Thanks for support menubar repository 🙏 

Are there some ways to migrate my projects builded in "old" menubar to your system?

Thanks

PD: I am quite new with node and yarn 😅

**Comment by amaurymartiny** [comment]
Hello @yceballost, no problem.

#### Step 1: Remove old menubar and add new one

```bash
yarn remove menubar
yarn add @amaurymartiny/menubar
```

#### Step 2: Code change

Everywhere you did `var menubar = require('menubar')` as per the old docs, you need to replace it with `var { menubar } = require('@amaurymartiny/menubar')`. Notice the `{}` around `menubar`. You can also use ES6/TS syntax as documented in the [CHANGELOG](https://github.com/amaurymartiny/menubar/blob/master/CHANGELOG.md#breaking-changes).

And that should be it! Let me know if you encounter any problems.

**Comment by yceballost** [comment]
> var { menubar } = require('@amaurymartiny/menubar')

It's doesn't works for me, but I use `var menubar = require('@amaurymartiny/menubar').menubar;` and everything is right

**Comment by amaurymartiny** [comment]
Ah, you're correct! The `{...}` syntax has been introduced in es6 too. I've [updated](https://github.com/amaurymartiny/menubar/pull/13/files) the change log for future reference.
