### ISSUE TITLE
Unable to add window event listener + Electron 5 support

### ISSUE THREAD

**Issue by vkolova** [amaurymartiny/menubar#14]
Hello!

I'd like to use this project and implement a tray menu that behaves as much as a native context menu as possible. For this to happen I need to add some event listener to the window that menubar creates, but it doesn't seem to work for me.

For example:
```javascript
const mb = menubar();
mb.on('ready', function ready () {
   console.log('app is ready');
    mb.window.on('blur', () => {
         mb.window.hide();
   });
});
```
Does nothing.

Another thing is that Electron v5 came out. When I updated to 5, the menubar package stopped working (it doesn't load anything, can't even open devTools on the window).

**Comment by amaurymartiny** [comment]
That's because, at `mb.on('ready')`, `mb.window` is not created created.

There are 2 solutions:

1. Use `preloadWindow` in [options](https://github.com/amaurymartiny/menubar#options). This means that before clicking on the tray icon, we already preload the window.
2. Use `.on('after-create-window')`:
```javascript
const mb = menubar();
mb.on('after-create-window', function ready () {
   console.log('app is ready');
    mb.window.on('blur', () => {
         mb.window.hide();
   });
});
```

I also updated electron to allow v4 and v5 in #15

**Comment by amaurymartiny** [comment]
Released in [`@amaurymartiny/menubar@6.0.1`](https://www.npmjs.com/package/@amaurymartiny/menubar/v/6.0.1) 🚀

**Comment by vkolova** [comment]
Thanks! I was unable to make it work even with `after-create-window` (came out I was using `preloadpreloadWindow` after all). But I got it working with `focus-lost`.

**Comment by vkolova** [comment]
I am still unable to use the package with Electron 5. I think it's because `nodeIntegration` now defaults to `false` and I need to be able to use it in my project. Adding a way to pass more than just the documented options would be nice, since webContents can't be changed after window creation.

**Comment by amaurymartiny** [comment]
Actually, now, you can pass nodeIntegration into Menubar's options. It's not documented, it's not a recommended way, but you can do it:

```javascript
const mb = new Menubar({ nodeIntegration: true });
```

All the options that are passed into Menubar, and are not consumed by Menubar, are passed down into the BrowserWindow constructor.

I find this behavior super confusing and prone to errors, so I want to change it: #17. You can do this trick above for now, or, I'll be able to publish a v6.0.2 to solve #17 this weekend.
